apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatvault.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chatvault.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-user: {{ .Values.postgresUser | quote }}
  postgres-password: {{ .Values.postgresPassword | quote }}
  private-key: {{ .Values.jwtPrivateKey | quote }}
  database-url: "postgres://{{ .Values.postgresUser }}:{{ .Values.postgresPassword }}@{{ include "chatvault.fullname" . }}-postgres:5432/{{ .Values.postgres.db }}?sslmode=disable"
